// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX5vJD2hs9v1jrVETW4mO9K2Gb1zaFRes',
    appId: '1:831359682433:web:bc18bf2dabb33d68a74a80',
    messagingSenderId: '831359682433',
    projectId: 'cert-7fffc',
    authDomain: 'cert-7fffc.firebaseapp.com',
    storageBucket: 'cert-7fffc.firebasestorage.app',
    measurementId: 'G-N19JPJ0H3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANZcvneFUVk_6witkW1vRsG3K9LfQUpZA',
    appId: '1:831359682433:android:dd390cec43c569cea74a80',
    messagingSenderId: '831359682433',
    projectId: 'cert-7fffc',
    storageBucket: 'cert-7fffc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKZwIXi74ZZHQIjC4GBLu7y-hFYSe-jO4',
    appId: '1:831359682433:ios:b3c89eaafdd492f9a74a80',
    messagingSenderId: '831359682433',
    projectId: 'cert-7fffc',
    storageBucket: 'cert-7fffc.firebasestorage.app',
    iosBundleId: 'com.example.flutterGroupProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKZwIXi74ZZHQIjC4GBLu7y-hFYSe-jO4',
    appId: '1:831359682433:ios:b3c89eaafdd492f9a74a80',
    messagingSenderId: '831359682433',
    projectId: 'cert-7fffc',
    storageBucket: 'cert-7fffc.firebasestorage.app',
    iosBundleId: 'com.example.flutterGroupProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX5vJD2hs9v1jrVETW4mO9K2Gb1zaFRes',
    appId: '1:831359682433:web:cf421c08786dc0b4a74a80',
    messagingSenderId: '831359682433',
    projectId: 'cert-7fffc',
    authDomain: 'cert-7fffc.firebaseapp.com',
    storageBucket: 'cert-7fffc.firebasestorage.app',
    measurementId: 'G-WS3S783FSD',
  );
}
